---
- name: Beeper
  identifier:
    kind: exe
    id: Beeper.exe
  options:
    - border_overflow
    - tray_and_multi_window
- name: Discord
  identifier:
    kind: exe
    id: Discord.exe
  options:
    - border_overflow
    - tray_and_multi_window
- name: Google Chrome
  identifier:
    kind: exe
    id: chrome.exe
  options:
    - tray_and_multi_window
- name: IntelliJ IDEA
  identifier:
    kind: exe
    id: idea64.exe
  options:
    - object_name_change
    - tray_and_multi_window
  float_identifiers:
    - kind: class
      id: SunAwtDialog
      comment: Targets JetBrains IDE popups and floating windows
- name: Microsoft Excel
  identifier:
    kind: exe
    id: EXCEL.EXE
  options:
    - border_overflow
    - layered
  float_identifiers:
    - kind: class
      id: _WwB
      comment: Targets a hidden window spawned by Microsoft Office applications
- name: Microsoft Word
  identifier:
    kind: exe
    id: WINWORD.EXE
  options:
    - border_overflow
    - layered
  float_identifiers:
    - kind: class
      id: _WwB
      comment: Targets a hidden window spawned by Microsoft Office applications
- name: Mozilla Firefox
  identifier:
    kind: exe
    id: firefox.exe
  options:
    - object_name_change
    - tray_and_multi_window
- name: Obsidian
  identifier:
    kind: exe
    id: Obsidian.exe
  options:
    - border_overflow
    - force
- name: PyCharm
  identifier:
    kind: exe
    id: pycharm64.exe
  options:
    - object_name_change
    - tray_and_multi_window
  float_identifiers:
    - kind: class
      id: SunAwtDialog
      comment: Targets JetBrains IDE popups and floating windows
- name: Slack
  identifier:
    kind: exe
    id: slack.exe
  options:
    - border_overflow
    - force
    - tray_and_multi_window
- name: Spotify
  identifier:
    kind: exe
    id: Spotify.exe
  options:
    - border_overflow
    - tray_and_multi_window
